name: roman-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - astropy
  - jupyter
  - jupyterlab
  - s3fs
  - fsspec
  - asdf
  - dask
  - pip:
    # Roman-specific packages (install via pip as they may not be in conda)
    - roman-datamodels
    - romancal
    - romanisim
    - stpsf
    - crds
    - synphot
    - stsynphot
    - astroquery
    - photutils
    - galsim
    - jdaviz
    - pandeia.engine
    - pysiaf

variables:
  # CRDS (Calibration Reference Data System) Configuration
  # Server URL for Roman CRDS
  CRDS_SERVER_URL: "https://roman-crds.stsci.edu"
  
  # Local path for CRDS cache directory
  # Update this path to match your preferred cache location
  CRDS_PATH: "${HOME}/.crds_cache"
  
  # CRDS context file (optional - will use latest if not specified)
  # Update this value when you want to use a specific context
  CRDS_CONTEXT: "roman_latest.pmap"
  
  # Synphot/STSynphot Configuration
  # Path to Synphot calibration database
  # Update this path to your synphot data location
  PYSYN_CDBS: "${HOME}/.synphot_data"
  
  # AWS Configuration (for S3 access)
  # Most notebooks use anonymous access, but these can be set if needed
  # AWS_ACCESS_KEY_ID: "your_access_key_here"
  # AWS_SECRET_ACCESS_KEY: "your_secret_key_here"
  AWS_DEFAULT_REGION: "us-east-1"
  
  # Performance/Threading Configuration
  # Limit threading to prevent resource exhaustion
  OMP_NUM_THREADS: "4"
  MKL_NUM_THREADS: "4" 
  NUMBA_NUM_THREADS: "4"
  
  # Additional Roman-specific settings
  # Disable CRDS automatic context updates (optional)
  CRDS_AUTO_UPDATE_CONTEXT: "false"
  
  # Set log level for CRDS operations
  CRDS_VERBOSITY: "50"
